# Generated by Django 4.0.1 on 2022-02-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_search', '0002_alter_mostsearch_search_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostsearch',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
