# Generated by Django 4.0.1 on 2022-02-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_search', '0003_mostsearch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostsearch',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity'),
        ),
    ]
